# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b09660f221438499e41570f5936007e9135488533b2014eea6e2f62949b2667096bdccf944d3d9ad16a87d27f3ce8a5f577dffa2e006fd52ced9ce614284774c

test:
  secret_key_base: 2e06405d12ef811fb7146bf13a041d3b604f34782a253699c0315929281023a3e19e4583a91a24f5b878fcf37690215afd8e4c25a986ae63a5618b4f59826fc2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
